name: Release

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test

    permissions:
      contents: read
      actions: read

    uses: ./.github/workflows/test.yml

  deploy:
    name: Deploy

    needs:
      - test

    uses: ./.github/workflows/deploy.yml

    secrets: inherit
